code --extensions-dir ./ext --user-data-dir ./data --install-extension  bmewburn.vscode-intelephense-client
code --extensions-dir ./ext --user-data-dir ./data --install-extension  felixfbecker.php-debug
code --extensions-dir ./ext --user-data-dir ./data --install-extension  felixfbecker.php-intellisense
code --extensions-dir ./ext --user-data-dir ./data --install-extension  ikappas.composer
code --extensions-dir ./ext --user-data-dir ./data --install-extension  ikappas.phpcs
code --extensions-dir ./ext --user-data-dir ./data --install-extension  linyang95.php-symbols
code --extensions-dir ./ext --user-data-dir ./data --install-extension  mehedidracula.php-namespace-resolver
code --extensions-dir ./ext --user-data-dir ./data --install-extension  neilbrayfield.php-docblocker
code --extensions-dir ./ext --user-data-dir ./data --install-extension  persoderlind.vscode-phpcbf
code --extensions-dir ./ext --user-data-dir ./data --install-extension  rexshi.phpdoc-comment-vscode-plugin
code --extensions-dir ./ext --user-data-dir ./data --install-extension  wk-j.save-and-run
code --extensions-dir ./ext --user-data-dir ./data --install-extension  wordpresstoolbox.wordpress-toolbox
code --extensions-dir ./ext --user-data-dir ./data --install-extension  yogensia.searchwpdocs
code --extensions-dir ./ext --user-data-dir ./data --install-extension  yzhang.markdown-all-in-one
